acceleration: 500.0
feedrate: 1500.0
home_position:
  X: 1.0
  Y: 2.0
  Z: 3.0
jerk: 10.0
max_acceleration:
  E: 9888.0
  X: 499.0
  Y: 500.0
  Z: 100.0
max_feedrate:
  E: 25.0
  X: 500.0
  Y: 500.0
  Z: 5.0
motor_current: 800.0
steps_per_mm:
  E: 93.0
  X: 80.0
  Y: 80.0
  Z: 400.0
